# Generated by Django 6.1 on 2026-08-19 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionistApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_document', models.FileField(upload_to='nutritionist/licenses/')),
                ('specialization', models.CharField(max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ai_review', 'AI Review'), ('ai_approved', 'AI Approved'), ('ai_rejected', 'AI Rejected'), ('admin_approved', 'Admin Approved'), ('admin_rejected', 'Admin Rejected')], default='pending', max_length=30)),
                ('ai_verified', models.BooleanField(default=False)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('ai_result', models.JSONField(blank=True, null=True)),
                ('ai_verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reviewed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_nutritionist_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
