# Generated by Django 6.1 on 2026-08-19 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritionistapplication',
            old_name='admin_notes',
            new_name='rejection_reason',
        ),
        migrations.RenameField(
            model_name='nutritionistapplication',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='nutritionistapplication',
            name='admin_reviewed',
        ),
        migrations.RemoveField(
            model_name='nutritionistapplication',
            name='ai_confidence',
        ),
        migrations.RemoveField(
            model_name='nutritionistapplication',
            name='ai_verified',
        ),
        migrations.RemoveField(
            model_name='nutritionistapplication',
            name='ai_verified_at',
        ),
        migrations.RemoveField(
            model_name='nutritionistapplication',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='nutritionistapplication',
            name='license_document',
        ),
        migrations.RemoveField(
            model_name='nutritionistapplication',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='ai_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='credential_document',
            field=models.FileField(blank=True, null=True, upload_to='nutritionist_documents/'),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='current_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='full_name',
            field=models.CharField(default='default@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='phone',
            field=models.CharField(default='Mara@exapmle.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritionistapplication',
            name='license_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritionistapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='NutritionistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('license_number', models.CharField(max_length=255, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='nutritionists/profile/')),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
