# Generated by Django 6.1 on 2026-08-24 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0002_rename_admin_notes_nutritionistapplication_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionistapplication',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='nutritionistapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='coverage_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='credential_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='credential_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='degree_document',
            field=models.FileField(blank=True, null=True, upload_to='nutritionist_documents/degrees/'),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='nutritionist_documents/insurance/'),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='insurance_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='nutritionist_documents/licenses/'),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='license_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='license_jurisdiction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistapplication',
            name='policy_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nutritionistapplication',
            name='credential_document',
            field=models.FileField(blank=True, null=True, upload_to='nutritionist_documents/credentials/'),
        ),
        migrations.AlterField(
            model_name='nutritionistapplication',
            name='current_role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritionistapplication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='nutritionistapplication',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nutritionistapplication',
            name='phone',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='DegreeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
                ('document', models.FileField(upload_to='nutritionist_documents/degrees/')),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='pending', max_length=30)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='degree_credential', to='nutritionists.nutritionistapplication')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_provider', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=255, unique=True)),
                ('expiration_date', models.DateField()),
                ('coverage_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('document', models.FileField(upload_to='nutritionist_documents/insurance/')),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='pending', max_length=30)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_certificate', to='nutritionists.nutritionistapplication')),
            ],
        ),
        migrations.CreateModel(
            name='NationalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(max_length=255)),
                ('credential_number', models.CharField(max_length=255, unique=True)),
                ('document', models.FileField(upload_to='nutritionist_documents/national_credentials/')),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='pending', max_length=30)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='national_credential', to='nutritionists.nutritionistapplication')),
            ],
        ),
        migrations.CreateModel(
            name='StateLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=255, unique=True)),
                ('jurisdiction', models.CharField(max_length=255)),
                ('expiration_date', models.DateField()),
                ('document', models.FileField(upload_to='nutritionist_documents/licenses/')),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='pending', max_length=30)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state_license', to='nutritionists.nutritionistapplication')),
            ],
        ),
    ]
