# Generated by Django 4.2.29 on 2026-08-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staffapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffapplication',
            name='password',
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='credential_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/credentials/'),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='degree_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/degrees/'),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/insurance/'),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/licenses/'),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
