# Generated by Django 4.2.29 on 2026-08-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_staffapplication_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapplication',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
