# Generated by Django 6.1 on 2026-08-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_nutritionistavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
